# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0009_gcmdevice_rename_device_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcmdevice',
            name='device_id',
            field=models.TextField(blank=True, db_index=True, default='', help_text='ANDROID_ID / TelephonyManager.getDeviceId()', null=True, verbose_name='Device ID'),
        ),
    ]
